DATASET:
  TRAIN_IMAGE_FOLDER: ""
  TRAIN_LABEL_FOLDER: ""
  TEST_IMAGE_FOLDER: ""
  TEST_LABEL_FOLDER: ""
  BAND_LIST: [1, 2, 3]
  WINDOW_SIZE: (256, 256)
  AUGMENTATION: True
  CLASS_NUM: 3
  TRAIN_DATASET_SIZE: 1000
  WITH_LABEL: True

TRAIN:
  DEVICE: "new device"
  EPOCH: 100
  BATCH_SIZE: 4
  SHUFFLE: True
  INPUT_CHANNEL: 3
  OPTIMIZER: "SGD"
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.00004
  LOSS_OUT_IDX: 100
  LOSS_SAVE_PATH: ""
  MODEL_SAVE_ITER: 10
  MODEL_SAVE_PATH: ""

TEST:
  DEVICE: ""
  STRIDE: 128
  MODEL_LOAD_PATH: ""
  PREDICT_SAVE_PATH: ""
  CONFUSION_MATRIX_SAVE_PATH: ""

#'cuda:0' if torch.cuda.is_available() else 'cpu'
