DATASET:
  TRAIN_IMAGE_DIR: ""
  TRAIN_LABEL_DIR: ""
  TEST_IMAGE_DIR: ""
  TEST_LABEL_DIR: ""
  BAND_LIST: [ 1, 2, 3 ]
  WINDOW_SIZE: (256, 256)
  TRAIN_DATASET_SIZE: 1000
  AUGMENTATION: False
  CLASS_NUM: 3
  WITH_LABEL: True
  LABELS: [ 0,1,2 ]

TRAIN:
  DEVICE: "cuda:0"
  EPOCH: 100
  BATCH_SIZE: 4
  INPUT_CHANNEL_NUM: 3
  OPTIMIZER: "SGD"
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.00004
  LOSS_OUT_ITER: 100
  LOSS_SAVE_DIR: ""
  MODEL_SAVE_ITER: 10
  MODEL_SAVE_DIR: ""

TEST:
  DEVICE: "cuda:0"
  STRIDE: 128
  BATCH_SIZE: 4
  MODEL_LOAD_DIR: ""
  PREDICT_SAVE_DIR: ""
  CONFUSION_MATRIX_SAVE_DIR: ""

#'cuda:0' if torch.cuda.is_available() else 'cpu'
